var gostek_data = [
/*  ID                              FILE                      P1  P2     CX    CY  VISIBLE FLEX FLIP  TEAM   COLOR         ALPHA  */
["SECONDARY_DEAGLES",         "",                              5, 10,    0.3,  0.5,   0,    0,    1,    0,   "NONE",       "BASE" ],
["SECONDARY_MP5",             "weapons-gfx/mp5",               5, 10,    0.3,  0.3,   0,    0,    1,    0,   "NONE",       "BASE" ],
["SECONDARY_AK74",            "weapons-gfx/ak74",              5, 10,    0.3, 0.25,   0,    0,    1,    0,   "NONE",       "BASE" ],
["SECONDARY_STEYR",           "weapons-gfx/steyraug",          5, 10,    0.3,  0.5,   0,    0,    1,    0,   "NONE",       "BASE" ],
["SECONDARY_SPAS",            "weapons-gfx/spas12",            5, 10,    0.3,  0.3,   0,    0,    1,    0,   "NONE",       "BASE" ],
["SECONDARY_RUGER",           "weapons-gfx/ruger77",           5, 10,    0.3,  0.3,   0,    0,    1,    0,   "NONE",       "BASE" ],
["SECONDARY_M79",             "weapons-gfx/m79",               5, 10,    0.3, 0.35,   0,    0,    1,    0,   "NONE",       "BASE" ],
["SECONDARY_BARRETT",         "weapons-gfx/barretm82",         5, 10,    0.3, 0.35,   0,    0,    1,    0,   "NONE",       "BASE" ],
["SECONDARY_MINIMI",          "weapons-gfx/m249",              5, 10,    0.3, 0.35,   0,    0,    1,    0,   "NONE",       "BASE" ],
["SECONDARY_MINIGUN",         "weapons-gfx/minigun",           5, 10,    0.2,  0.5,   0,    0,    1,    0,   "NONE",       "BASE" ],
["SECONDARY_SOCOM",           "",                              5, 10,    0.3,  0.5,   0,    0,    1,    0,   "NONE",       "BASE" ],
["SECONDARY_KNIFE",           "",                              5, 10,    0.3,  0.5,   0,    0,    1,    0,   "NONE",       "BASE" ],
["SECONDARY_CHAINSAW",        "weapons-gfx/chainsaw",          5, 10,   0.25, 0.35,   0,    0,    1,    0,   "NONE",       "BASE" ],
["SECONDARY_LAW",             "weapons-gfx/law",               5, 10,    0.3, 0.45,   0,    0,    1,    0,   "NONE",       "BASE" ],
["SECONDARY_FLAMEBOW",        "",                              5, 10,    0.3,  0.5,   0,    0,    1,    0,   "NONE",       "BASE" ],
["SECONDARY_BOW",             "",                              5, 10,    0.3,  0.5,   0,    0,    1,    0,   "NONE",       "BASE" ],
["SECONDARY_FLAMER",          "weapons-gfx/flamer",            5, 10,    0.3,  0.3,   0,    0,    1,    0,   "NONE",       "BASE" ],
["LEFT_THIGH",                "gostek-gfx/udo",                6,  3,    0.2,  0.5,   1,    5,    1,    1,   "PANTS",      "BASE" ],
["LEFT_THIGH_DMG",            "gostek-gfx/ranny/udo",          6,  3,    0.2,  0.5,   0,    5,    1,    1,   "NONE",       "BLOOD"],
["LEFT_FOOT",                 "gostek-gfx/stopa",              2, 18,   0.35, 0.35,   1,    0,    1,    1,   "NONE",       "BASE" ],
["LEFT_JETFOOT",              "gostek-gfx/lecistopa",          2, 18,   0.35, 0.35,   0,    0,    1,    1,   "NONE",       "BASE" ],
["LEFT_LOWERLEG",             "gostek-gfx/noga",               3,  2,   0.15, 0.55,   1,    0,    1,    1,   "PANTS",      "BASE" ],
["LEFT_LOWERLEG_DMG",         "gostek-gfx/ranny/noga",         3,  2,   0.15, 0.55,   0,    0,    1,    1,   "NONE",       "BLOOD"],
["LEFT_ARM",                  "gostek-gfx/ramie",             11, 14,      0,  0.5,   1,    0,    1,    1,   "MAIN",       "BASE" ],
["LEFT_ARM_DMG",              "gostek-gfx/ranny/ramie",       11, 14,      0,  0.5,   0,    0,    1,    1,   "NONE",       "BLOOD"],
["LEFT_FOREARM",              "gostek-gfx/reka",              14, 15,      0,  0.5,   1,    5,    0,    1,   "MAIN",       "BASE" ],
["LEFT_FOREARM_DMG",          "gostek-gfx/ranny/reka",        14, 15,      0,  0.5,   0,    5,    1,    1,   "NONE",       "BLOOD"],
["LEFT_HAND",                 "gostek-gfx/dlon",              15, 19,      0,  0.4,   1,    0,    1,    1,   "SKIN",       "BASE" ],
["GRABBED_HELMET",            "gostek-gfx/helm",              15, 19,      0,  0.5,   0,    0,    1,    1,   "MAIN",       "BASE" ],
["GRABBED_HAT",               "gostek-gfx/kap",               15, 19,    0.1,  0.4,   0,    0,    1,    1,   "MAIN",       "BASE" ],
["RIGHT_THIGH",               "gostek-gfx/udo",                5,  4,    0.2, 0.65,   1,    5,    1,    1,   "PANTS",      "BASE" ],
["RIGHT_THIGH_DMG",           "gostek-gfx/ranny/udo",          5,  4,    0.2, 0.65,   0,    5,    1,    1,   "NONE",       "BLOOD"],
["RIGHT_FOOT",                "gostek-gfx/stopa",              1, 17,   0.35, 0.35,   1,    0,    1,    1,   "NONE",       "BASE" ],
["RIGHT_JETFOOT",             "gostek-gfx/lecistopa",          1, 17,   0.35, 0.35,   0,    0,    1,    1,   "NONE",       "BASE" ],
["RIGHT_LOWERLEG",            "gostek-gfx/noga",               4,  1,   0.15, 0.55,   1,    0,    1,    1,   "PANTS",      "BASE" ],
["RIGHT_LOWERLEG_DMG",        "gostek-gfx/ranny/noga",         4,  1,   0.15, 0.55,   0,    0,    1,    1,   "NONE",       "BLOOD"],
["CHEST",                     "gostek-gfx/klata",             10, 11,    0.1,  0.3,   1,    0,    1,    1,   "MAIN",       "BASE" ],
["VEST",                      "gostek-gfx/kamizelka",         10, 11,    0.1,  0.3,   0,    0,    1,    1,   "NONE",       "BASE" ],
["CHEST_DMG",                 "gostek-gfx/ranny/klata",       10, 11,    0.1,  0.3,   0,    0,    1,    1,   "NONE",       "BLOOD"],
["HIP",                       "gostek-gfx/biodro",             5,  6,   0.25,  0.6,   1,    0,    1,    1,   "MAIN",       "BASE" ],
["HIP_DMG",                   "gostek-gfx/ranny/biodro",       5,  6,   0.25,  0.6,   0,    0,    1,    1,   "NONE",       "BLOOD"],
["HEAD",                      "gostek-gfx/morda",              9, 12,      0,  0.5,   1,    0,    1,    1,   "SKIN",       "BASE" ],
["HEAD_DMG",                  "gostek-gfx/ranny/morda",        9, 12,      0,  0.5,   0,    0,    1,    1,   "HEADBLOOD",  "BLOOD"],
["HEAD_DEAD",                 "gostek-gfx/morda",              9, 12,    0.5,  0.5,   0,    0,    1,    1,   "SKIN",       "BASE" ],
["HEAD_DEAD_DMG",             "gostek-gfx/ranny/morda",        9, 12,    0.5,  0.5,   0,    0,    1,    1,   "HEADBLOOD",  "BLOOD"],
["MR_T",                      "gostek-gfx/hair3",              9, 12,      0,  0.5,   0,    0,    1,    1,   "HAIR",       "BASE" ],
["HELMET",                    "gostek-gfx/helm",               9, 12,      0,  0.5,   0,    0,    1,    1,   "MAIN",       "BASE" ],
["HAT",                       "gostek-gfx/kap",                9, 12,      0,  0.5,   0,    0,    1,    1,   "MAIN",       "BASE" ],
["RAMBO_BADGE",               "gostek-gfx/badge",              9, 12,      0,  0.5,   0,    0,    1,    1,   "NONE",       "BASE" ],
["HAIR_DREADLOCKS",           "gostek-gfx/hair1",              9, 12,      0,  0.5,   0,    0,    1,    1,   "HAIR",       "BASE" ],
["HAIR_DREADLOCK1",           "gostek-gfx/dred",              23, 24,    0.5,    0,   0,    0,    0,    1,   "HAIR",       "BASE" ],
["HAIR_DREADLOCK2",           "gostek-gfx/dred",              23, 24,    0.5,  0.8,   0,    0,    0,    1,   "HAIR",       "BASE" ],
["HAIR_DREADLOCK3",           "gostek-gfx/dred",              23, 24,    0.4, -0.8,   0,    0,    0,    1,   "HAIR",       "BASE" ],
["HAIR_DREADLOCK4",           "gostek-gfx/dred",              23, 24,   0.65, -0.5,   0,    0,    0,    1,   "HAIR",       "BASE" ],
["HAIR_DREADLOCK5",           "gostek-gfx/dred",              23, 24,    0.3, -1.3,   0,    0,    0,    1,   "HAIR",       "BASE" ],
["HAIR_PUNK",                 "gostek-gfx/hair2",              9, 12,      0,  0.5,   0,    0,    1,    1,   "HAIR",       "BASE" ],
["HAIR_NORMAL",               "gostek-gfx/hair4",              9, 12,      0,  0.5,   0,    0,    1,    1,   "HAIR",       "BASE" ],
["CIGAR",                     "gostek-gfx/cygaro",             9, 12, -0.125,  0.4,   0,    0,    1,    1,   "CYGAR",      "BASE" ],
["SILVER_LCHAIN",             "gostek-gfx/lancuch",           10, 22,    0.1,  0.5,   0,    0,    0,    1,   "NONE",       "BASE" ],
["SILVER_RCHAIN",             "gostek-gfx/lancuch",           11, 22,    0.1,  0.5,   0,    0,    0,    1,   "NONE",       "BASE" ],
["SILVER_PENDANT",            "gostek-gfx/metal",             22, 21,    0.5,  0.7,   0,    0,    1,    1,   "NONE",       "BASE" ],
["GOLDEN_LCHAIN",             "gostek-gfx/zlotylancuch",      10, 22,    0.1,  0.5,   0,    0,    0,    1,   "NONE",       "BASE" ],
["GOLDEN_RCHAIN",             "gostek-gfx/zlotylancuch",      11, 22,    0.1,  0.5,   0,    0,    0,    1,   "NONE",       "BASE" ],
["GOLDEN_PENDANT",            "gostek-gfx/zloto",             22, 21,    0.5,  0.5,   0,    0,    1,    1,   "NONE",       "BASE" ],
["FRAG_GRENADE1",             "weapons-gfx/frag-grenade",      5,  6,    0.5,    0,   0,    0,    0,    0,   "NONE",       "NADES"],
["FRAG_GRENADE2",             "weapons-gfx/frag-grenade",      5,  6,    0.5,    0,   0,    0,    0,    0,   "NONE",       "NADES"],
["FRAG_GRENADE3",             "weapons-gfx/frag-grenade",      5,  6,    0.5,    0,   0,    0,    0,    0,   "NONE",       "NADES"],
["FRAG_GRENADE4",             "weapons-gfx/frag-grenade",      5,  6,    0.5,    0,   0,    0,    0,    0,   "NONE",       "NADES"],
["FRAG_GRENADE5",             "weapons-gfx/frag-grenade",      5,  6,    0.5,    0,   0,    0,    0,    0,   "NONE",       "NADES"],
["CLUSTER_GRENADE1",          "weapons-gfx/cluster-grenade",   5,  6,    0.5,    0,   0,    0,    0,    0,   "NONE",       "NADES"],
["CLUSTER_GRENADE2",          "weapons-gfx/cluster-grenade",   5,  6,    0.5,    0,   0,    0,    0,    0,   "NONE",       "NADES"],
["CLUSTER_GRENADE3",          "weapons-gfx/cluster-grenade",   5,  6,    0.5,    0,   0,    0,    0,    0,   "NONE",       "NADES"],
["CLUSTER_GRENADE4",          "weapons-gfx/cluster-grenade",   5,  6,    0.5,    0,   0,    0,    0,    0,   "NONE",       "NADES"],
["CLUSTER_GRENADE5",          "weapons-gfx/cluster-grenade",   5,  6,    0.5,    0,   0,    0,    0,    0,   "NONE",       "NADES"],
["PRIMARY_DEAGLES",           "weapons-gfx/deserteagle",      16, 15,    0.1,  0.8,   0,    0,    1,    0,   "NONE",       "BASE" ],
["PRIMARY_DEAGLES_CLIP",      "weapons-gfx/deserteagle-clip", 16, 15,    0.1,  0.8,   0,    0,    1,    0,   "NONE",       "BASE" ],
["PRIMARY_DEAGLES_FIRE",      "weapons-gfx/eagles-fire",      16, 15,   -0.4, 1.15,   0,    0,    0,    0,   "NONE",       "BASE" ],
["PRIMARY_MP5",               "weapons-gfx/mp5",              16, 15,   0.15,  0.6,   0,    0,    1,    0,   "NONE",       "BASE" ],
["PRIMARY_MP5_CLIP",          "weapons-gfx/mp5-clip",         16, 15,   0.15,  0.6,   0,    0,    1,    0,   "NONE",       "BASE" ],
["PRIMARY_MP5_FIRE",          "weapons-gfx/mp5-fire",         16, 15,  -0.65, 0.85,   0,    0,    0,    0,   "NONE",       "BASE" ],
["PRIMARY_AK74",              "weapons-gfx/ak74",             16, 15,   0.15,  0.5,   0,    0,    1,    0,   "NONE",       "BASE" ],
["PRIMARY_AK74_CLIP",         "weapons-gfx/ak74-clip",        16, 15,   0.15,  0.5,   0,    0,    1,    0,   "NONE",       "BASE" ],
["PRIMARY_AK74_FIRE",         "weapons-gfx/ak74-fire",        16, 15,  -0.37,  0.8,   0,    0,    0,    0,   "NONE",       "BASE" ],
["PRIMARY_STEYR",             "weapons-gfx/steyraug",         16, 15,   0.25,  0.7,   0,    0,    1,    0,   "NONE",       "BASE" ],
["PRIMARY_STEYR_CLIP",        "weapons-gfx/steyraug-clip",    16, 15,   0.25,  0.7,   0,    0,    1,    0,   "NONE",       "BASE" ],
["PRIMARY_STEYR_FIRE",        "weapons-gfx/steyraug-fire",    16, 15,   -0.2,  0.9,   0,    0,    0,    0,   "NONE",       "BASE" ],
["PRIMARY_SPAS",              "weapons-gfx/spas12",           16, 15,    0.1,  0.6,   0,    0,    1,    0,   "NONE",       "BASE" ],
["PRIMARY_SPAS_CLIP",         "",                             16, 15,      0,    0,   0,    0,    1,    0,   "NONE",       "BASE" ],
["PRIMARY_SPAS_FIRE",         "weapons-gfx/spas12-fire",      16, 15,   -0.2,  0.9,   0,    0,    0,    0,   "NONE",       "BASE" ],
["PRIMARY_RUGER",             "weapons-gfx/ruger77",          16, 15,    0.1,  0.7,   0,    0,    1,    0,   "NONE",       "BASE" ],
["PRIMARY_RUGER_CLIP",        "",                             16, 15,      0,    0,   0,    0,    1,    0,   "NONE",       "BASE" ],
["PRIMARY_RUGER_FIRE",        "weapons-gfx/ruger77-fire",     16, 15,  -0.35, 0.85,   0,    0,    0,    0,   "NONE",       "BASE" ],
["PRIMARY_M79",               "weapons-gfx/m79",              16, 15,    0.1,  0.7,   0,    0,    1,    0,   "NONE",       "BASE" ],
["PRIMARY_M79_CLIP",          "weapons-gfx/m79-clip",         16, 15,      0,    0,   0,    0,    1,    0,   "NONE",       "BASE" ],
["PRIMARY_M79_FIRE",          "weapons-gfx/m79-fire",         16, 15,   -0.4,  0.8,   0,    0,    0,    0,   "NONE",       "BASE" ],
["PRIMARY_BARRETT",           "weapons-gfx/barretm82",        16, 15,   0.15,  0.7,   0,    0,    1,    0,   "NONE",       "BASE" ],
["PRIMARY_BARRETT_CLIP",      "weapons-gfx/barretm82-clip",   16, 15,   0.15,  0.7,   0,    0,    1,    0,   "NONE",       "BASE" ],
["PRIMARY_BARRETT_FIRE",      "weapons-gfx/barret-fire",      16, 15,  -0.15,  0.8,   0,    0,    0,    0,   "NONE",       "BASE" ],
["PRIMARY_MINIMI",            "weapons-gfx/m249",             16, 15,   0.15,  0.6,   0,    0,    1,    0,   "NONE",       "BASE" ],
["PRIMARY_MINIMI_CLIP",       "weapons-gfx/m249-clip",        16, 15,   0.15,  0.6,   0,    0,    1,    0,   "NONE",       "BASE" ],
["PRIMARY_MINIMI_FIRE",       "weapons-gfx/m249-fire",        16, 15,   -0.2,  0.9,   0,    0,    0,    0,   "NONE",       "BASE" ],
["PRIMARY_MINIGUN_CLIP",      "weapons-gfx/minigun-clip",      8,  7,    2.2,    0,   0,    0,    0,    0,   "NONE",       "BASE" ],
["PRIMARY_MINIGUN",           "weapons-gfx/minigun",          16, 15,   0.05,  0.5,   0,    0,    1,    0,   "NONE",       "BASE" ],
["PRIMARY_MINIGUN_FIRE",      "weapons-gfx/minigun-fire",     16, 15,   -0.2, 0.45,   0,    0,    0,    0,   "NONE",       "BASE" ],
["PRIMARY_SOCOM",             "weapons-gfx/colt1911",         16, 15,    0.1,  0.6,   0,    0,    1,    0,   "NONE",       "BASE" ],
["PRIMARY_SOCOM_CLIP",        "weapons-gfx/colt1911-clip",    16, 15,      0,    0,   0,    0,    1,    0,   "NONE",       "BASE" ],
["PRIMARY_SOCOM_FIRE",        "weapons-gfx/colt1911-fire",    16, 15,   -0.3,  0.9,   0,    0,    0,    0,   "NONE",       "BASE" ],
["PRIMARY_KNIFE",             "weapons-gfx/knife",            16, 20,   -0.1,  0.6,   0,    0,    1,    0,   "NONE",       "BASE" ],
["PRIMARY_KNIFE_CLIP",        "",                             16, 15,      0,    0,   0,    0,    1,    0,   "NONE",       "BASE" ],
["PRIMARY_KNIFE_FIRE",        "",                             16, 15,      0,    0,   0,    0,    1,    0,   "NONE",       "BASE" ],
["PRIMARY_CHAINSAW",          "weapons-gfx/chainsaw",         16, 15,    0.1,  0.5,   0,    0,    1,    0,   "NONE",       "BASE" ],
["PRIMARY_CHAINSAW_CLIP",     "",                             16, 15,      0,    0,   0,    0,    1,    0,   "NONE",       "BASE" ],
["PRIMARY_CHAINSAW_FIRE",     "weapons-gfx/chainsaw-fire",    16, 15,      0,    0,   0,    0,    0,    0,   "NONE",       "BASE" ],
["PRIMARY_LAW",               "weapons-gfx/law",              16, 15,    0.1,  0.6,   0,    0,    1,    0,   "NONE",       "BASE" ],
["PRIMARY_LAW_CLIP",          "",                             16, 15,      0,    0,   0,    0,    1,    0,   "NONE",       "BASE" ],
["PRIMARY_LAW_FIRE",          "weapons-gfx/law-fire",         16, 15,   -0.1, 0.55,   0,    0,    0,    0,   "NONE",       "BASE" ],
["PRIMARY_BOW",               "weapons-gfx/bow",              16, 15,   -0.4, 0.55,   0,    0,    1,    0,   "NONE",       "BASE" ],
["PRIMARY_BOW_ARROW",         "weapons-gfx/bow-a",            16, 15,      0, 0.55,   0,    0,    0,    0,   "NONE",       "BASE" ],
["PRIMARY_BOW_STRING",        "weapons-gfx/bow-s",            16, 15,   -0.4, 0.55,   0,    0,    0,    0,   "NONE",       "BASE" ],
["PRIMARY_BOW_RELOAD",        "weapons-gfx/bow",              16, 15,   -0.4, 0.55,   0,    0,    1,    0,   "NONE",       "BASE" ],
["PRIMARY_BOW_ARROW_RELOAD",  "weapons-gfx/arrow",            16, 20,      0, 0.55,   0,    0,    0,    0,   "NONE",       "BASE" ],
["PRIMARY_BOW_STRING_RELOAD", "weapons-gfx/bow-s",            16, 15,   -0.4, 0.55,   0,    0,    0,    0,   "NONE",       "BASE" ],
["PRIMARY_BOW_FIRE",          "weapons-gfx/bow-fire",         16, 15,      0,    0,   0,    0,    0,    0,   "NONE",       "BASE" ],
["PRIMARY_FLAMER",            "weapons-gfx/flamer",           16, 15,    0.2,  0.7,   0,    0,    1,    0,   "NONE",       "BASE" ],
["PRIMARY_FLAMER_CLIP",       "",                             16, 15,      0,    0,   0,    0,    1,    0,   "NONE",       "BASE" ],
["PRIMARY_FLAMER_FIRE",       "weapons-gfx/flamer-fire",      16, 15,      0,    0,   0,    0,    0,    0,   "NONE",       "BASE" ],
["RIGHT_ARM",                 "gostek-gfx/ramie",             10, 13,   -0.1,  0.5,   1,    0,    1,    1,   "MAIN",       "BASE" ],
["RIGHT_ARM_DMG",             "gostek-gfx/ranny/ramie",       10, 13,   -0.1,  0.5,   0,    0,    1,    1,   "NONE",       "BLOOD"],
["RIGHT_FOREARM",             "gostek-gfx/reka",              13, 16,      0,  0.6,   1,    5,    0,    1,   "MAIN",       "BASE" ],
["RIGHT_FOREARM_DMG",         "gostek-gfx/ranny/reka",        13, 16,      0,  0.6,   0,    5,    1,    1,   "NONE",       "BLOOD"],
["RIGHT_HAND",                "gostek-gfx/dlon",              16, 20,      0,  0.5,   1,    0,    1,    1,   "SKIN",       "BASE" ]
];
